# Generated by Django 4.2.8 on 2024-02-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('staff_Id', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='UserRegistration',
        ),
    ]
